# Data Loading: Arxiv Dataset

Data source: https://www.kaggle.com/datasets/spsayakpaul/arxiv-paper-abstracts/data

## Setup

In [1]:
# Check Python version
!python --version

Python 3.13.9

In [4]:
# %pip install torch==2.9.1 torchvision --index-url https://download.pytorch.org/whl/cu128

In [6]:
# Load / save the list of installed libraries
# %pip freeze > new_requirements.txt
# %pip install -r requirements.txt

In [12]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [13]:
# Set CUDA_VISIBLE_DEVICES before importing torch
seed = 42

np.random.seed(seed)
os.environ['PYTHONHASHSEED'] = str(seed)
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

## Handle input data

In [14]:
# Import libraries
import json
from pathlib import Path
from pandas import json_normalize

In [15]:
df = pd.read_csv(f'raw/arxiv_data.csv')

df

,titles,summaries,terms
0,Survey on Semantic Stereo Matching / Semantic ...,Stereo matching is one of the widely used tech...,"['cs.CV', 'cs.LG']"
1,FUTURE-AI: Guiding Principles and Consensus Re...,The recent advancements in artificial intellig...,"['cs.CV', 'cs.AI', 'cs.LG']"
2,Enforcing Mutual Consistency of Hard Regions f...,"In this paper, we proposed a novel mutual cons...","['cs.CV', 'cs.AI']"
3,Parameter Decoupling Strategy for Semi-supervi...,Consistency training has proven to be an advan...,['cs.CV']
4,Background-Foreground Segmentation for Interio...,"To ensure safety in automated driving, the cor...","['cs.CV', 'cs.LG']"
...,...,...,...
51769,Hierarchically-coupled hidden Markov models fo...,We address the problem of analyzing sets of no...,"['stat.ML', 'physics.bio-ph', 'q-bio.QM']"
51770,Blinking Molecule Tracking,We discuss a method for tracking individual mo...,"['cs.CV', 'cs.DM']"
51771,Towards a Mathematical Foundation of Immunolog...,We attempt to set a mathematical foundation of...,"['stat.ML', 'cs.LG', 'q-bio.GN']"
51772,A Semi-Automatic Graph-Based Approach for Dete...,Diffusion Tensor Imaging (DTI) allows estimati...,['cs.CV']
51773,SparseCodePicking: feature extraction in mass ...,Mass spectrometry (MS) is an important techniq...,"['stat.ML', 'physics.med-ph', 'stat.AP', 'stat..."

In [16]:
df = df.rename(columns={'summaries': 'text'})
               
df

,titles,text,terms
0,Survey on Semantic Stereo Matching / Semantic ...,Stereo matching is one of the widely used tech...,"['cs.CV', 'cs.LG']"
1,FUTURE-AI: Guiding Principles and Consensus Re...,The recent advancements in artificial intellig...,"['cs.CV', 'cs.AI', 'cs.LG']"
2,Enforcing Mutual Consistency of Hard Regions f...,"In this paper, we proposed a novel mutual cons...","['cs.CV', 'cs.AI']"
3,Parameter Decoupling Strategy for Semi-supervi...,Consistency training has proven to be an advan...,['cs.CV']
4,Background-Foreground Segmentation for Interio...,"To ensure safety in automated driving, the cor...","['cs.CV', 'cs.LG']"
...,...,...,...
51769,Hierarchically-coupled hidden Markov models fo...,We address the problem of analyzing sets of no...,"['stat.ML', 'physics.bio-ph', 'q-bio.QM']"
51770,Blinking Molecule Tracking,We discuss a method for tracking individual mo...,"['cs.CV', 'cs.DM']"
51771,Towards a Mathematical Foundation of Immunolog...,We attempt to set a mathematical foundation of...,"['stat.ML', 'cs.LG', 'q-bio.GN']"
51772,A Semi-Automatic Graph-Based Approach for Dete...,Diffusion Tensor Imaging (DTI) allows estimati...,['cs.CV']
51773,SparseCodePicking: feature extraction in mass ...,Mass spectrometry (MS) is an important techniq...,"['stat.ML', 'physics.med-ph', 'stat.AP', 'stat..."

In [17]:
# Drop rows where 'text' is missing or empty
df = df.dropna(subset=['text']).reset_index(drop=True)
df = df[df['text'].astype(str).str.strip() != '']

df

,titles,text,terms
0,Survey on Semantic Stereo Matching / Semantic ...,Stereo matching is one of the widely used tech...,"['cs.CV', 'cs.LG']"
1,FUTURE-AI: Guiding Principles and Consensus Re...,The recent advancements in artificial intellig...,"['cs.CV', 'cs.AI', 'cs.LG']"
2,Enforcing Mutual Consistency of Hard Regions f...,"In this paper, we proposed a novel mutual cons...","['cs.CV', 'cs.AI']"
3,Parameter Decoupling Strategy for Semi-supervi...,Consistency training has proven to be an advan...,['cs.CV']
4,Background-Foreground Segmentation for Interio...,"To ensure safety in automated driving, the cor...","['cs.CV', 'cs.LG']"
...,...,...,...
51769,Hierarchically-coupled hidden Markov models fo...,We address the problem of analyzing sets of no...,"['stat.ML', 'physics.bio-ph', 'q-bio.QM']"
51770,Blinking Molecule Tracking,We discuss a method for tracking individual mo...,"['cs.CV', 'cs.DM']"
51771,Towards a Mathematical Foundation of Immunolog...,We attempt to set a mathematical foundation of...,"['stat.ML', 'cs.LG', 'q-bio.GN']"
51772,A Semi-Automatic Graph-Based Approach for Dete...,Diffusion Tensor Imaging (DTI) allows estimati...,['cs.CV']
51773,SparseCodePicking: feature extraction in mass ...,Mass spectrometry (MS) is an important techniq...,"['stat.ML', 'physics.med-ph', 'stat.AP', 'stat..."

In [18]:
df = df.drop_duplicates(subset=['text']).reset_index(drop=True)

df

,titles,text,terms
0,Survey on Semantic Stereo Matching / Semantic ...,Stereo matching is one of the widely used tech...,"['cs.CV', 'cs.LG']"
1,FUTURE-AI: Guiding Principles and Consensus Re...,The recent advancements in artificial intellig...,"['cs.CV', 'cs.AI', 'cs.LG']"
2,Enforcing Mutual Consistency of Hard Regions f...,"In this paper, we proposed a novel mutual cons...","['cs.CV', 'cs.AI']"
3,Parameter Decoupling Strategy for Semi-supervi...,Consistency training has proven to be an advan...,['cs.CV']
4,Background-Foreground Segmentation for Interio...,"To ensure safety in automated driving, the cor...","['cs.CV', 'cs.LG']"
...,...,...,...
38974,A Ray-based Approach for Boundary Estimation o...,Diffusion Tensor Imaging (DTI) is a non-invasi...,['cs.CV']
38975,Statistical Denoising for single molecule fluo...,Single molecule fluorescence microscopy is a p...,['cs.CV']
38976,Blinking Molecule Tracking,We discuss a method for tracking individual mo...,"['cs.CV', 'cs.DM']"
38977,Towards a Mathematical Foundation of Immunolog...,We attempt to set a mathematical foundation of...,"['stat.ML', 'cs.LG', 'q-bio.GN']"
38978,A Semi-Automatic Graph-Based Approach for Dete...,Diffusion Tensor Imaging (DTI) allows estimati...,['cs.CV']

In [41]:
print(df['text'][0])

Stereo matching is one of the widely used techniques for inferring depth from
stereo images owing to its robustness and speed. It has become one of the major
topics of research since it finds its applications in autonomous driving,
robotic navigation, 3D reconstruction, and many other fields. Finding pixel
correspondences in non-textured, occluded and reflective areas is the major
challenge in stereo matching. Recent developments have shown that semantic cues
from image segmentation can be used to improve the results of stereo matching.
Many deep neural network architectures have been proposed to leverage the
advantages of semantic segmentation in stereo matching. This paper aims to give
a comparison among the state of art networks both in terms of accuracy and in
terms of speed which are of higher importance in real-time applications.

In [21]:
# Save dataframe to .csv file
df.to_csv('complete/arxiv.csv', index=False)

In [ ]:
# Processing with data_cleaning.py

In [31]:
df_text = pd.read_parquet(f'processed/parquet/arxiv_text.parquet')

In [32]:
df_text

                                                    text
0      Stereo matching is one of the widely used tech...
1      The recent advancements in artificial intellig...
2      In this paper, we proposed a novel mutual cons...
3      Consistency training has proven to be an advan...
4      To ensure safety in automated driving, the cor...
...                                                  ...
38974  Diffusion Tensor Imaging (DTI) is a non-invasi...
38975  Single molecule fluorescence microscopy is a p...
38976  We discuss a method for tracking individual mo...
38977  We attempt to set a mathematical foundation of...
38978  Diffusion Tensor Imaging (DTI) allows estimati...

[38979 rows x 1 columns]

In [33]:
display(df_text.head())
print('DataFrame shape:', df_text.shape)

                                                text
0  Stereo matching is one of the widely used tech...
1  The recent advancements in artificial intellig...
2  In this paper, we proposed a novel mutual cons...
3  Consistency training has proven to be an advan...
4  To ensure safety in automated driving, the cor...

DataFrame shape: (38979, 1)

In [34]:
# Print dataset statistics
avg_chars = df_text['text'].apply(lambda x: len(str(x))).mean()
print("Average number of characters for text passage:", avg_chars)
avg_words = df_text['text'].apply(lambda x: len(x.split(" "))).mean()
print("Average number of words for text passage:", avg_words)
print("Average word length:", avg_chars / avg_words)

Average number of characters for text passage: 1191.8400420739372
Average number of words for text passage: 171.68939685471665
Average word length: 6.941838365723136

In [ ]:
# Convert 'text' column into list containing documents
docs = df_text['text'].tolist()

In [49]:
# Ensure all documents are strings
for i in range(len(docs)):
    docs[i] = str(docs[i])

In [37]:
# Print length of the document list
print("Number of documents:", len(docs))

Number of documents: 38979

In [38]:
# Print a sample of document
print(docs[9])

The success of deep learning methods in medical image segmentation tasks heavily depends on a large amount of labeled data to supervise the training. On the other hand, the annotation of biomedical images requires domain knowledge and can be laborious. Recently, contrastive learning has demonstrated great potential in learning latent representation of images even without any label. Existing works have explored its application to biomedical image segmentation where only a small portion of data is labeled, through a pre-training phase based on self-supervised contrastive learning without using any labels followed by a supervised fine-tuning phase on the labeled portion of data only. In this paper, we establish that by including the limited label in formation in the pre-training phase, it is possible to boost the performance of contrastive learning. We propose a supervised local contrastive loss that leverages limited pixel-wise annotation to force pixels with the same label to gather around in the embedding space. Such loss needs pixel-wise computation which can be expensive for large images, and we further propose two strategies, downsampling and block division, to address the issue. We evaluate our methods on two public biomedical image datasets of different modalities. With different amounts of labeled data, our methods consistently outperform the state-of-the-art contrast-based methods and other semi-supervised learning techniques.

In [42]:
labels = df['terms'].tolist()

labels

["['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.HC']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', '68U10, 62M05, 62H30, 65C20']",
 "['cs.CV']",
 "['cs.CV', 'cs.NE']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'physics.geo-ph']",
 "['cs.LG']",
 "['cs.CV']",
 "['cs.LG', '60D05, 62C99']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV', 'cs.RO']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'I.4.6']",
 "['cs.LG', 'cs.CR']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.RO']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', '49-06 (Primary), 49-11(Secondary)', 'I.4.6; I.5.1']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['stat.ML', 'cs.LG']",
 "['cs.LG', 'cs.AI', 'cs.CV', 'stat.ME', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'stat.ML', '68T01', 'I.2.0; I.5.0']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'q-bio.TO']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', '68T07', 'I.4.6']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.CR', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'q-bio.NC']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'q-bio.QM']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.AI']",
 "['cs.LG', 'cs.CR', 'cs.NE', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.AI', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'cs.AI', 'cs.CV']",
 "['cs.CV', 'cs.NI', 'cs.RO', 'eess.SP']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.CR', 'cs.LG']",
 "['cs.CV']",
 "['cs.LG', 'cs.AI', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.CR', 'cs.LG']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['stat.ML', 'cs.CL', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.CL', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.GR', 'cs.RO']",
 "['cs.CV', 'cs.MM']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CY']",
 "['cs.CV', 'cs.MM']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.NA', 'math.NA']",
 "['cs.CV', 'cs.CG']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CG']",
 "['cs.CV']",
 "['cs.CV', 'cs.AR']",
 "['stat.ML', 'cs.LG']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'I.4.6; I.2.6; I.5.4; I.5.1']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.LG', 'cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'cs.NE', 'cs.RO', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV', 'cs.CG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.LG', 'cs.NA', 'math.NA', 'stat.ML', '68R10, 05C50, 65F15, 65T50, 68T05, 62H30']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.RO', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'eess.IV', 'stat.ML', 'I.4.6; I.2.6']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.MM']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'physics.geo-ph', 'I.4.6; I.4.3']",
 "['cs.LG', 'cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.IT', 'math.IT', 'Computing methodologies for image processing', 'I.4']",
 "['cs.CV', 'eess.IV', 'stat.AP', '62P99']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.CG', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'cs.MM']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'cs.NE', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'stat.AP']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['stat.ML', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.GT']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', '68T45', 'J.6; J.0']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.LG', 'cs.MM', 'eess.IV', 'I.4.6; I.2.10; I.5.0; I.3.0; E.0']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CL']",
 "['cs.CV', 'eess.IV']",
 "['cs.LG', 'eess.IV', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.CL']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.DC', 'cs.LG', 'cs.NE', 'eess.IV']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV', 'cs.HC']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['stat.ML', 'cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.GR']",
 "['cs.CV', '68T45 (Primary) 68T07 (Secondary)', 'I.4.6']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'I.2.1, I.4.6,']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.RO']",
 "['cs.CV']",
 "['cs.CV', 'cs.NA', 'math.NA']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CR']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'J.3']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'I.2.10']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', '62H30', 'I.4.6']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'I.5; I.5.4; I.4; I.4.6; I.4.8; I.4.9']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV', 'I.4; I.5']",
 "['cs.CV']",
 "['cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CY', 'cs.LG']",
 "['cs.CV', 'cs.LG', 'eess.IV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CY', 'I.4.6; J.2']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'eess.IV']",
 "['cs.LG', 'cs.AI', 'cs.CV', 'stat.ML', 'I.5.1; I.2.1; I.5.3; J.3; G.1.6']",
 "['cs.CV']",
 "['cs.LG', 'eess.SP', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.LG', 'cs.CV', 'eess.IV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', '68U10', 'I.4.6']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.RO']",
 "['cs.CV']",
 "['cs.CV', 'cs.CL', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CL', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['stat.ML', 'cs.LG', 'q-fin.CP', '60G40, 65C60, 68T99']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.LG']",
 "['cs.LG', 'cs.CL', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.AP', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'cs.NE']",
 "['cs.CV', '62H30', 'I.4.6']",
 "['cs.CV', '68U10']",
 "['cs.LG', 'stat.ML']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'eess.IV']",
 "['cs.LG', 'cs.NE']",
 "['cs.CV', 'cond-mat.stat-mech']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.LG', 'stat.ML']",
 "['cs.LG', 'math.OC', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'cs.NE', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'E.1; I.4; I.5; I.6']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CG']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'I.4.6, I.5.4', 'I.4.6; I.5.4']",
 "['cs.CV', 'cs.LG', 'math.ST', 'stat.ML', 'stat.TH']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.SY']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.SP']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'stat.ML']",
 "['cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'cs.RO', 'eess.IV']",
 "['cs.CV']",
 "['cs.LG', 'eess.SP', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', '68U10']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'cs.NE']",
 "['cs.CV']",
 "['cs.LG', 'cs.AI', 'stat.ML']",
 "['cs.LG', 'cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.NE']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'cs.AI', 'cs.CV', 'cs.SY', 'eess.SY', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['stat.ML', 'cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.NA', 'math.NA']",
 "['cs.CV', '68T45']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.CG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.DS']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'q-bio.TO']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.RO']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.RO', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.LG', 'cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'cs.LG', 'cs.NE']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.NA', 'math.NA']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'eess.IV']",
 "['cs.LG', 'cs.CV', 'eess.IV', 'stat.ML']",
 "['cs.CV', 'cs.CG']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CG', 'cs.LG']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'physics.med-ph']",
 "['cs.CV', 'cs.SD', 'eess.AS', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV']",
 "['cs.CV', 'eess.IV', 'G.1.6']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CL']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CL', 'cs.LG']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.LG', 'eess.IV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.RO']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CG', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.GR', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'cs.CR']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'cs.NE']",
 "['cs.CV']",
 "['cs.CV', 'cs.GR', 'cs.NE']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'cs.PF', 'stat.ML', 'C.4; I.2.6; I.2.10; I.4.6; I.4.9; J.4']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', '65K05, 62F10, 65D19']",
 "['cs.CV']",
 "['cs.LG', 'math.NA', 'stat.ML', '68R10, 05C50, 65F15, 65T50, 68T05, 62H30']",
 "['cs.CV']",
 "['cs.LG', 'math.OC', 'stat.ML', '65K10, 68T45']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.LG', 'cs.DC', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', 'cs.GR', 'cs.LG']",
 "['stat.ML', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.RO', 'cs.SY']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'q-bio.QM', 'q-bio.TO']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.CR', 'cs.LG']",
 "['cs.CV']",
 "['cs.LG', 'cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV', 'cs.RO']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'math.NA']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['stat.ML', 'cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'eess.IV', 'stat.ML']",
 "['cs.CV', 'cs.LG', 'cs.NE', '68T45']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV', '68U10, 68W99', 'I.4.6; I.4.5']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.CL', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.LG', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI', 'cs.GR', 'cs.LG']",
 "['cs.LG']",
 "['cs.CV', 'cs.NE']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.AI']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV', 'stat.ML']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'eess.IV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['stat.ML', 'cs.CV', 'cs.LG', 'cs.NE']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV', 'cs.LG']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",
 "['cs.CV']",

In [40]:
nan_count = 0

for i in range(len(labels)):
    if pd.isna(labels[i]):
        nan_count += 1

print("Number of NaN labels:", nan_count)

Number of NaN labels: 0

In [43]:
import ast

In [44]:
dict_labels = dict()

for i in range(len(labels)):

    if(pd.notna(labels[i])):
        label = ast.literal_eval(labels[i])

        for j in range(len(label)):
            if label[j] not in dict_labels:
                dict_labels[label[j]] = 1
            else:
                dict_labels[label[j]] += 1


print("Unique labels:", list(dict_labels.keys()))
print("Label counts:", list(dict_labels.values()))

Unique labels: ['cs.CV', 'cs.LG', 'cs.AI', 'cs.HC', '68U10, 62M05, 62H30, 65C20', 'cs.NE', 'eess.IV', 'physics.geo-ph', '60D05, 62C99', 'cs.RO', 'I.4.6', 'cs.CR', '49-06 (Primary), 49-11(Secondary)', 'I.4.6; I.5.1', 'stat.ML', 'stat.ME', '68T01', 'I.2.0; I.5.0', 'q-bio.TO', '68T07', 'q-bio.NC', 'q-bio.QM', 'cs.NI', 'eess.SP', 'cs.CL', 'cs.GR', 'cs.MM', 'cs.CY', 'cs.NA', 'math.NA', 'cs.CG', 'cs.AR', 'I.4.6; I.2.6; I.5.4; I.5.1', '68R10, 05C50, 65F15, 65T50, 68T05, 62H30', 'I.4.6; I.2.6', 'I.4.6; I.4.3', 'cs.IT', 'math.IT', 'Computing methodologies for image processing', 'I.4', 'stat.AP', '62P99', 'cs.GT', '68T45', 'J.6; J.0', 'I.4.6; I.2.10; I.5.0; I.3.0; E.0', 'cs.DC', '68T45 (Primary) 68T07 (Secondary)', 'I.2.1, I.4.6,', 'J.3', 'I.2.10', '62H30', 'I.5; I.5.4; I.4; I.4.6; I.4.8; I.4.9', 'I.4; I.5', 'I.4.6; J.2', 'I.5.1; I.2.1; I.5.3; J.3; G.1.6', '68U10', 'q-fin.CP', '60G40, 65C60, 68T99', 'cond-mat.stat-mech', 'math.OC', 'E.1; I.4; I.5; I.6', 'I.4.6, I.5.4', 'I.4.6; I.5.4', 'math.ST', 'stat.TH', 'cs.SY', 'eess.SY', 'cs.DS', 'physics.med-ph', 'cs.SD', 'eess.AS', 'G.1.6', 'cs.PF', 'C.4; I.2.6; I.2.10; I.4.6; I.4.9; J.4', '65K05, 62F10, 65D19', '65K10, 68T45', '68U10, 68W99', 'I.4.6; I.4.5', 'cs.IR', '68T05, 68T45', 'I.2.6; I.4.6; I.5.5', 'physics.data-an', 'stat.CO', 'cs.DM', 'math.PR', '26A33', 'I.2.10; I.2.6', 'I.2.6; I.5.1; I.5.4; I.4.6', '68T10', 'I.4.7; I.4.8; I.5.1', '05B45, 62H30, 54E05, 68T10', '54E40', 'I.4.7; I.4.6; G.2.2; I.2.10; G.1.2', 'math.AP', '68', 'hep-ex', '68U01', '49Q10, 62H35', 'cond-mat.dis-nn', 'C.1.3', '65Kxx, 65Yxx', 'G.1.0; G.1.6', '62P10, 62F15', 'cs.CE', '94A08, 68U10, 65K10, 35K55, 49Q10', 'math.RA', '68U10, 05C85', 'quant-ph', 'I.4.6; G.1.8', 'astro-ph', 'cs.SE', 'I.4.8; I.4.6; I.4.0; I.2.9; I.2.10; J.2.; I.5.5; I.5.4; I.4.9', 'physics.chem-ph', 'physics.ao-ph', 'I.2.6; J.2', 'cs.SI', 'nlin.CG', '68T07 (Primary) 68T45 (Secondary)', 'hep-th', '68T07 (Primary) 68T01 (Secondary)', 'A.1; I.2.6', 'I.4.9; I.5.4', 'q-bio.MN', 'q-fin.ST', '62, 68', 'q-bio.GN', 'astro-ph.HE', 'gr-qc', '68T10, 62H30', 'I.2; I.4; I.5', '6804 (Primary)', 'I.2', 'H.0; I.0; I.2', 'math.FA', 'I.3.5; I.2.10', 'I.2.6', 'I.2.10; I.4.10', 'I.2.6; I.5.5', '68T07, 68T30, 65D15, 91G80, 62H25, 62G08, 57-08', 'cs.MS', 'cs.PL', 'math.AT', 'q-bio.BM', 'G.2.6; I.2.2', '68T05 (Primary) 62H12, 68T07 (Secondary)', 'J.2', 'math.CT', '03B70, 03-04, 03D10, 11Y16', 'cs.MA', 'I.2.10; I.5.4', 'cs.DB', 'I.4.8; I.2.6', 'I.4.m, I.5.4, I.5.1, I.2.1', 'I.2.6; I.2.10; I.5.0; J.4', 'I.2.7; I.2.6; I.3.7', 'math.DG', 'physics.comp-ph', 'cond-mat.soft', '62P12', 'I.2; J.2', 'F.2.4', 'I.2.10; I.4; I.5', 'I.5.1; I.5.2; I.5.4', '68T30', 'I.5.4', 'math.CA', 'I.2.7; I.2.10', 'I.2.7; I.2.1; J.2; J.3', 'math.SP', 'I.2; H.0', 'I.4; I.5; I.2', 'cs.DL', 'cs.SC', 'I.5.1', 'I.2.4', 'physics.soc-ph', '68T05', 'I.2.0; I.2.6; I.5.1; J.2', 'nlin.CD', '97R40', 'J.4; I.2.4', 'math.AC', 'I.2.0; I.2.6; I.2.4', '14J60', 'F.2.2', '68T30, 68T05, 62-07l', 'I.2.0; I.2.4; I.2.6; G.3', '68T30 (Primary), 68T01 (Secondary)', 'I.5.2', 'math.DS', 'I.5.1; G.1.6; H.2.8', 'I.2.6; H.5.5', 'I.2.6; I.4', 'cs.LO', 'K.3.2', '68U10 (Primary) 94A08, 54H30 (Secondary)', 'I.4.3; I.4.4', 'I.4.4', 'I.2.6; I.5.1', 'I.4.0; I.2.6', 'I.2.10; I.4.4; I.5.4', 'I.2.10; I.2.9; I.2.6', 'I.4.0; I.2.9; I.2.6; G.3; I.3.3', 'I.4; I.2', '68Txx, 68-XX', 'I.4; I.5; I.3; I.2', '68M25, 68T05', 'cond-mat.mtrl-sci', 'I.4.9; I.4.10', 'I.2; I.2.10', 'I.4.9; I.4.8; I.3.3', '68-06', 'I.4.0; I.5.4', 'physics.app-ph', 'physics.ins-det', 'I.4.7', 'I.2.10; I.4.8', 'physics.optics', 'I.2.10; I.4.9', 'I.2.6; I.2.10; I.0; I.4.0', '03B52, 94A08', 'I.4.8; I.4.10', 'I.2; I.4', 'I.4.7; I.5.1', 'This paper tells us how human can be identified by their Gait cycle\n  using any simple camera', 'I.4.8', 'I.2.1; I.2.10; I.4.6; I.4.9; J.2; J.6', '68T07, 65D19', 'I.4.0; I.2.10', 'cs.CC', 'I.2, I.4', 'I.2.10; I.4.8; I.5', 'I.2; I.2.6; I.2.10; I.4', '68T50, 68T45', 'I.2.6; I.2.10; I.4.9; I.5.1; I.5.4', 'I.4.0; I.4.3; I.4.6; I.4.9; I.4.m', 'I.2.10; I.2.10; I.2.1; I.4.6; I.4.7; I.4.8; I.4.9; I.5.2; I.5.5', 'I.4.7; I.4.9; I.4.10; I.5.2; I.5.3; I.5.4; I.2.4; I.2.6; I.2.10;\n  H.3.1; H.3.3', '68T45, 68T07', 'I.4.8; I.4.9; I.2.10', 'I.2.6; I.4.6; I.5.1', '68T45 (Primary),', 'I.5; I.5.4; I.4; I.4.7; I.4.8; I.4.9', 'I.2.10; I.4.8; I.4.9; I.4.10; I.5.4; K.4.4', 'I.4.9; I.2; J.7', '68-04', 'I.2.10; I.4.6; I.2.7', 'q-bio.PE', 'Artificial intelligence', 'I.3.5; I.3.7; I.4.7; I.4.10; I.5.4', 'astro-ph.IM', '68T45, 68T40', 'I.2.10; I.2.6; I.2.9', 'cs.ET', '68T04', '65D19', 'I.4.8; I.2.10; I.5.2; I.5.1', 'I.4.0', '68T40, 68T45, 68T01', 'I.2.10; I.2.9; I.4.8; I.5.2; I.4.0', 'I.4.8; I.5.2', 'I.2.10; I.4.7; I.4.8; I.4.9; I.5; I.5.2; I.5.4; I.5.5', 'I.4.6; I.4.8; I.5.4; I.2.10', 'D.2.2; I.2.10', 'I.4.8; I.4.9', 'I.4.9', 'I.4.9; I.5.2', '14J60 (Primary) 14F05, 14J26 (Secondary)', 'F.2.2; I.2.7', 'I.4; I.2; I.5', 'I.2.m', 'math.RT', '68T07 (Primary) 68Q55 (Secondary)', 'I.2.4; I.2.6; I.2.10; I.4.8; I.4.10; I.5.1', 'I.3; I.5', '68T07, 68T45', 'hep-ph', 'nucl-th', 'I.2.10; I.2.7; I.4.10', '65Z05', '35Q79, 74A40, 68T07, 65M22,', '68T07 (Primary), 68U10 (Secondary)', 'I.4; J.3', '62G05', 'I.6.5; J.6', '65D19 (Primary), 05C50 (Secondary)', 'physics.plasm-ph', 'I.2.7', 'I.4; I.2.10', 'H.1.2; I.4.8; I.4.9; J.2; J.4', '68T01, 68T40, 93C85', '68T01, 68T05, 68T07, 68T10, 62P15', 'I.2; I.2.0; I.2.6; I.2.7; I.2.11; I.5; I.5.1; I.5.2; I.5.4; I.4.10;\n  H.5.1; H.5.2; H.3.3', 'I.4.6; I.4.9; I.2.6; J.2', 'H.3.3; I.2.1; I.2.6; I.2.10; I.4.3; I.4.6; I.4.7; I.4.8; I.4.9;\n  I.5.1; I.5.2; I.5.4', 'I.4.6; I.4.9', 'q-fin.PM', 'q-fin.TR', '68T05 (Primary)', 'G.3; I.2; I.6', '68T50', '74S30 (primary), 74S05, 74B05, 74L05, 74L10 (secondary)', 'I.2.6; I.5.4', 'I.4.6; I.2.10; I.5.1', 'I.2.6; I.2.11', 'I.2.1; I.4.9', '68T99', 'q-fin.GN', '93E35', 'I.2.6; I.2.8', 'nucl-ex', 'I.2.6; I.5.0', 'I.2.6; I.2.7; I.2.10', 'I.2.6; F.m', 'I.2.6; I.2.8; I.5.0; J.2; J.3', '68T10, 68T45', 'I.4.8; I.5.4', '68T20', 'I.4.5; I.2.6', '68Q32, 68T05, 97C30, 46N30', 'H.2.8', 'I.5.2; I.5.3; I.5.4', 'I.6.5', '68T07, 86A10', 'physics.class-ph', 'J.2; D.2.11; E.1', 'econ.EM', '62H25, 62H99,', 'I.3.3', 'I.2.6; I.2.7', 'I.2.7; I.2.6', '68T50, 68T05', 'q-fin.MF', 'I.2.10; I.4.8; I.5.4', 'C.3; I.2; I.5', '68T07, 68T05, 68T27, 68T30', '35A18, 65T60, 68T10', 'I.4.0; I.4.1; I.4.7; I.4.8; I.4.9; I.4.10; I.2.10; I.5.1; I.5.2;\n  I.5.4', 'I.6.5; I.6.6; J.2; J.6', 'I.2.1; I.2.6', '68Q32, 68T05', 'I.2.6; G.3', 'D.2.0; I.2.5', 'J.3; I.5.1', 'I.2.1', 'I.5.1; I.4.6; I.2.6', '68W99', 'I.2.9; I.2.10; I.5.1', '92C55, 94A08, 94A15, 94A17, 68U10, 68W01', '62-XX, 92-XX, 68Txx,', 'J.3; I.2', '68T07, 05C85, 42C40', 'I.2.4; I.2.6', 'I.5.0; I.4.7', '37G05', '41A65, 46M40, 46M20, 46E30, 46M15, 68T07', 'I.5.1; F.2.1', '68T99, 65Z05, 65N06', 'I.2.6; G.1.8', 'I.2.10; I.2.7', '68T99, 65D15, 65M99, 65N99', '62G05, 62H20, 62H12, 62H30', 'I.4.7; I.4.8; I.5.0', '65Dxx', 'H.0', '60D05, 68T10, 68T05', 'I.4.6; I.4.8; I.4.9; I.5.4', 'nlin.PS', '60B20, 68T07', 'J.6; I.4.9; I.2.6', '68T37', 'G.3; I.2.0', '65D05, 53B20, 68U05', 'I.2.6; I.4.10', 'I.2.8; I.5.4; I.6.5', 'math.CV', 'I.2.10; I.3.3; I.3.5; G.1.4', 'I.4.9; J.3', '62J99 (Primary)', '60L10', 'G.3; I.2.4; I.2.6', '60H30, 68T99, 68N30', 'I.5', 'math.GR', '62G20, 68T05', '68Q32, 68T05, 68T07, 37M05, 37M10, 37M25', 'I.5.2; F.2.1; G.1.3; G.1.6', 'I.4.7; B.5.1; C.4.4', 'I.2; I.2.5', 'I.4.10; I.4.0; I.4.7', '35J50, 35Q68', 'Primary 60G60, 60H05, 62M15, Secondary 35K15', 'G.3; I.2.1; I.2.6; I.5.1; I.5.2; I.5.5; I.6.4; I.6.5; I.6.8; J.3', '62J02, 68T01, 62M45', '90C20, 90C27, 90C35, 90C90', 'I.4; I.6', 'physics.flu-dyn', '46E22, 62G08, 90C25', 'G.1.6; I.2.6', 'I.5.0; I.2.0', '68T07, 68T99', '65F55, 68T50, 68T01, 15A83', 'I.2.6; J.1', 'I.2.0; I.2.6', '68T07(Primary)', 'I.3.3; I.3.8; I.4.3; I.4.7; I.4.5; I.4.9; I.4.10; I.2.6; I.2.10', '62F15, 60G55, 62-07, and 62P10', 'I.2.6; I.2.10; I.4.6; I.4.7; I.4.10; I.5', 'I.4.1; I.4.9', '68U10, 68U15', 'cond-mat.str-el', 'math-ph', 'math.MP', 'A.1', 'I.2.0', 'I.4; I.5; H.5.1', 'G.3; I.2.6', 'econ.GN', 'q-fin.EC', '68Q32, 68T01', '68T07 (Primary) 68T05 (Secondary)', 'nlin.AO', '42C40, 05C85, 11Y16', 'cs.LG, cs.AI', 'I.4.0; I.2.7', '94A12, 94A08, 68U10, 65D18', '14R10, 15A63, 14L24, 15A69', 'I.5.2; I.2.6; E.1', '68U10, 68T10', 'G.1.6, I.2.6', '68T01 (Primary) 94A60 (Secondary)', 'H.3; I.4', '68U05', 'I.3.5; I.4.8; I.5.3', 'math.CO', 'I.2.10; I.3.7; I.4.8', 'J.3, I.2.6', 'J.3; I.2.6', 'I.2.5, G.3', 'I.2.5; G.3', '68T30, 68T05', 'I.2.7; I.2.4', 'I.2.10; I.3.5', 'I.5; I.5.4; I.3.3', '68Q25, 68R10, 68U05', 'q-bio.CB', 'q-fin.RM', '68W15', 'I.2.11', '68T10 (primary) 68T07, 68U10(secondary)', 'I.5.4; I.2.10; J.5', 'I.2.10; I.4.3; J.5', 'physics.bio-ph', '68T07, 62G07, 60-08', 'I.4.9; I.2.1', 'I.5.4; I.2.10', '86-08', 'I.1.5', 'I.2.10; I.3.3', 'J.6; I.4.9; I.2.10; J.5', '68T01 (Primary), 68T07 (Secondary)', 'I.5.0; I.4.0; G.3', '90-08, 68T01', 'I.2.6; I.5.1; I.4.0', '68T07, 60-08', 'I.2.11; I.2.6', 'I.4.2', '68T01, 68T50', 'I.2.0; I.2.7; I.5.0', 'I.3.0; J.4; I.2.6', 'I.4.6; I.2.6; J.3', '90C59, 90C90, 90-08, 60E05, 62E17', 'G.1.6; G.1.2; G.3; I.2.8; I.5; I.6; J.2', 'I.2.6; G.1.6', 'I.4.0; I.3.8', '65C05', 'I.2.6; I.6.8', 'I.2.10; I.3.7; I.4.1', 'astro-ph.GA', '68T05, 65L05, 37M10, 62M45, 68Q32', '68T10 (Primary) 68T20, 86-08, 86-04, 76T99 (Secondary)', 'I.5.1; I.6.3; I.5.4; I.2.8', '37M05, 37M10, 62M45, 68Q32, 68T05', 'I.4.7; I.4.10; I.5.4', 'I.2.10; I.4; I.4; I.2.6; D.4.6; E.3', '68T01, 68T05, 68U10, 62M45, 78M32, 92C55, 94A08', 'I.2; I.2.1; I.2.6; I.2.10; I.4.5; I.4.9', '68T01, 68T05, 68U10, 62M45, 78M32, 92C50, 92C55, 94A08', 'I.2; I.2.1; I.2.6; I.2.10; I.3; I.3.3; I.4.3; I.4.4; I.4.9; J.3', '65M06, 35K57, 35B50, 37N30', 'I.2.6; C.2', 'I.5.1; I.5.1', '68Txx', 'I.2.6; I.2; I.5', 'I.2.7; H.1.2; H.4.2; J.4', 'I.2.5; G.4', 'I.2.2; I.2.7; I.2.6; I.5.1', 'I.2.9', 'I.5.0, I.2.0', 'I.2.10; I.5.1; I.4.8', 'I.2; H.2', '68T45, 68T50', 'I.5.1; I.2.6', 'I.2.2', 'I.2.6; I.2.10; I.4.8; I.4.6', 'cs.FL', 'I.5.1; I.5.4', '62M45', '68U15, 68T50', '68T07 (Primary) 68T10, 68T45 (Secondary)', 'I.2.6; I.2.10', 'I.2.7; I.2.3', 'E.1; E.2; F.2.2; I.2.7', 'I.5.1; I.2.7', 'I.2.6; I.2.6', '62B10, 62B86, 94A15, 94A17, 62F15, 62F03', 'H.1.1; H.1.2; I.1.2; I.2.1; I.2.4; I.2.7; G.3', 'C.1.3; D.1.3; I.2.6; I.2.7; H.3.4', 'E.4', 'I.5.1; I.5.4; G.3; I.2.7; I.2.6', 'I.2.6; I.2.7; I.5.1; I.5.4; G.3', '62M09, 62P99, 68T50, 91F20, 03B65, 91E40, 60J20', 'H.3.1; I.2.6; I.2.7', 'I.2.6; I.2.7; H.3.1; J.5', 'H.5.2; I.5.4', 'I.2; I.2.6; I.2.7', 'I.2.6; H.2.8', '68T07, 68R10, 47A60', '05C50, 05C70, 65M55', 'I.2.6; H.4.0', 'I.5.3; G.2.2; I.2.6; G.1.2', '60L10, 60L20', 'I.5.3', '05C21, 68T07, 76D07, 76M10, 76S05', '62F12, 62H30, 68T10', 'I.4.5', 'I.5.3; I.2.6; I.2.2', 'J.2.4; J.3.1', '62J02, 65D15, 41A10', '05C20, 14T10, 62G32, 62H22, 05C99, 62R01, 65S05', '62H99', '62H22, 62D20', '62G20, 62H30, 60J27, 60J25, 35Q84, 58J35, 58J90, 28A33', 'I.2; I.5', 'G.2.2', 'I.2.6; I.5.4; J.2', 'I.6', '68T07 (Primary)', '37E25 (Primary) 68T30, 05C62, 58D10 (Secondary)', 'I.2.10; I.5.1; I.5.4', '62H22, 82B20, 94A17', '62H22, 62P30, 68T37, 80A30, 93B35, 94A17', 'econ.TH', '68T07, 68T45, 68T20', 'I.2.6; I.2.10; J.3', 'I.4.8; I.2.4; I.2.6', 'I.2.10; I.2.9', '68T01, 68T07, 68T30', 'I.2.6; I.2.4', 'I.5.3; I.5.1', 'math.MG', 'stat.OT', 'I.2.1; I.2.5', '68T07, 68T30, 68R99', 'I.2.0; I.2.4', 'astro-ph.CO', 'F.2.2; G.2.2; I.2.6', 'I.2.2; I.2.8', '05C85, 05C80', '62-02, 62-07, 62H25, 62H30, 94-02, 94C15', '62M10, 62H30, 62G99', '53Z50, 14M15, 60J20', '37M10, 68T07, 68T05, 68T37, 82C32', 'I.2; I.5; I.2.4; I.2.6; I.5.1', '68T07, 05C85', '68T07, 68T10', 'I.5.1; I.3.5', 'I.5.1; I.5.2', '05C62, 41A46, 41A63, 62J02', 'D.3.2; I.2.6', '16G20', 'F.4.1; I.2.4', 'C.3', '68N20', 'D.3.4', 'I.2.6; G.2.2', 'I.2; I.4; K.4; E.1', 'G.3; J.3; F.2.2', 'I.5.2; I.2.6', '35J20, 35R02, 65N12, 68T05', 'math.GT', '62F15, 90C35, 65F55, 68R10, 15B48', '05C99, 62M45', '90C26', 'I.3.7; G.3; I.2.6', '05C60', '10010147.10010257.10010258.10010259.10010263', '62h30, 68T05, 05C80', '68T40', '05C50', 'math.NT', '62H30, 91C20', 'C.4', '47B34', 'I.3.5; I.3.6; I.3.8; J.2', '90C26, 90C10, 90C17, 68Q87, 65C20', 'G.1.6; I.4.0', '68T10 (Primary), 42-08, 57Z25 (Secondary)', '68T01, 68T09', '62H22, 62R01, 62J99', 'I.2.1; J.3; J.6', '05C50, 68T07', 'I.6.4; I.5.3; I.4.6; I.2.4', '62F15, 62M05, 93E10', '68R10 (Primary), 90C27 (Secondary)', 'G.2.1; G.2.2', 'E.0', 'I.4.m I.2.7', '35J08, 35J15, 05C81, 68T05, 35R02', 'I.2.6; G.1.8; G.2.2; I.5.3; I.4.0', 'I.2.1 Applications and Expert Systems', '68-01, 90-01', '60J20 (Primary) 62F07, 68T05 (Secondary)', 'G.3; I.5.1', 'F.2.2; G.2.2', '68T40, 74Pxx, 46N10, 65D19', 'I.2.9; G.1.6; I.4.5; I.2.10', 'ams.org', 'J.5', '68T45, 68U05', 'I.3.6; I.2.10', '60J20, 91D30, 91C20, 62H30', 'I.4.6; I.4.10; I.2.6; I.2.10', '62H30, 68T10, 68Q87, 91C20', 'E.4; I.5.4', 'H.5.0; I.5.4; J.5', 'I.2.10; I.4.10; I.5.3', 'I.4; I.3', 'I.2.10; I.4; I.3', 'J.2; I.2.1', '68T45, 62F35', '68U10, 94A08', 'I.2.6; I.4.9; G.2.1; G.3; I.3.3', 'J.0', 'I.2.6; I.4.9', 'I.4.9; I.2.6', '65F55', 'G.1.3', 'K.4.2; J.m', 'I.4.1', 'I.2.10; I.4.6', '62H35, 94A08, 65K10, 35A15', '68T10, 68T37, 68T99', 'I.4.6; I.5.3', 'Computer science applications- 97R60 Computer graphics', 'q-bio.OT', 'I.2.10; I.4.6; I.4.8', 'H.4.m; J.4', '78', 'I.4.9; I.4.9; I.5.0; I.5.4', '43A32', 'I.4.6; I.4.8', 'I.4.7; I.4.8; I.4.9; I.5.1', '82C32 (Primary), 68T45 (Secondary)', 'H.5.1; I.4.8; I.5.1', '15A29, 65F22, 65K10, 68U10, 90C25, 90C46', 'I.2.6; I.4.9; J.5', 'I.4.7, I.4.8, I.5.1', 'I.2.10; I.3.7; I.4.1; I.4.8', 'math.HO', '15A60, 65F22, 65K10, 68U10, 90C25, 90C46, 94A08', 'H.2.8; H.3.3', '65F22', 'H.2.0', '15A69, 65D18, 68U05', 'I.4.3', '62-XX', '65F22, 65F50, 94A08', 'I.4.8, I.4.10, G.1.3, G.1.6', 'I.4.6; H.5.2', 'I.4.5; I.2.10', 'I.2.10; I.2.m', 'I.4.0; I.4.8; I.4.9; I.2.10', 'I.4.5; I.4.6; I.4.7; I.4.8', 'physics.ed-ph', 'physics.pop-ph', 'J.3; I.4.6', 'I.4.8; I.3.5; C.2.4', 'org', 'I.2.1; J.3', 'I.3.7; I.4.5', 'I.2.10; I.4.5; I.4.6; I.4.8; I.4.10', '55N31, 62R40, 55U10, 68T09', '68T45 68T07', '57Z25 (Primary) 55N31 (Secondary)', 'I.4.8; I.4.6; I.2.6; I.2.10', '65D18', '68U05, 68U10, 68U20, 65C50', 'G.1.3; I.4.10; I.4.8; J.2', 'I.2.10; I.3.0; I.4.8', 'I.4.6; I.4.8; I.2.9; I.2.10', 'H.2.8; I.2.6', '65D19, 68T45', 'I.4.6; I.2.10', '65T60', 'H.5.5; H.5.1; I.5', 'I.2.10; I.4.7; I.5.1', 'I.5.4; I.4.9; J.2', 'I.4.9; I.5.4; H.5.1; H.5.5', 'H.3.3; I.5.3', '65D17, 68U05, 68U10, 53A20', 'I.4.8; I.4.10; I.4.6; I.3.5; J.6', '53A04, 53A17, 53A20', 'I.4.8; I.3.5', 'I.2.10; I.3.5; I.4.1; I.4.8', '90C22, 52C25, 05C50', '62H30, 62G20, 49J55, 91C20, 68R10, 60D05', '68T45 (Primary) 68T10, 68T07 (Secondary)', 'I.4.9; I.5.4; I.2.10', '62H30 (Primary) 54F45 (Secondary)', '68Txx, 81Pxx', '62G08', 'math.OA', '62-07, 37H99', '37N99, 46E22, 47B32', '11Z05', 'H.3.3; E.2', 'I.4; I.5.1', '35A15, 35J47, 35Q68', 'I.2.9; I.2.10; I.4.1; I.4.10; I.5.4', '68T45 (Primary) 68U10 (Secondary)', 'I.4.9; I.4.8; I.2.10', '97R40, 68T45, 68Txx, 92B20', '2010', 'I.4; I.5; I.5.1', '65K10', '68U10, 65K10, 65M06', 'I.4; G.1.6; G.4', '68U10, 49M29, 65K10', 'B.7.1; I.2.6', 'I.2.6; I.2.10; I.4.8', '47N10, 35A15, 49N45, 65M20, 65J22, 68U10, 94A12, 65D18', 'I.2.6; I.4.8', 'I.4.6; I.4.7; I.4.8; I.5.1; I.5.4', 'I.2.10; I.4.6; I.4.8; I.5.4', 'E.5; E.4; E.2; H.1.1; F.1.1; F.1.3', '49J20, 68U10, 65D18', 'I.4.6; G.3', 'B.7.2', '68T01, 68T07', 'F.2.2; K.3.2', '91G70, 91-10, 91-08, 90C17, 93E35', 'I.2.8', '68T07 (Primary) 68Q42 (Secondary)', 'I.2.6; F.4.2', '68Tx', 'I.2.6; I.2.9', 'I.2.8; J.6', 'I.2.6; I.5.1; F.4.1', 'I.2.11; I.2.8', 'A.1; I.2.6; I.2.8; J.4', '91Bxx, 68Q32, 68T05, 93E35, 37N35', 'I.2.8; I.2.1', '94', 'H.5; I.4', '2020: 49N45, 93B30, 93E12, 93B15, 49N10, 90C40, 60J10, 62M05', '90-05, 90-06, 90-08, 90-10', 'I.2.6; I.2.8; J.7', '91B16', 'I.2.6; I.2.8; I.2.9', 'I.2.2; I.2.6', 'A.1; I.2.6; I.2.9; J.2', '68T07, 37N30, 68T05', '93Cxx', 'I.2.6; B.m', 'I.2.6; I.2', 'I.2.11; I.2.6; C.4', 'G.3', 'I.2.1; I.2.8; I.2.9', '68T05, 68T20', '68T05 (Primary) 68Q32, 68T42 (secondary)', 'physics.acc-ph', '68T40, 68T07', 'I.2.9; I.2.6; C.4', 'I.2.6, I.2.11', 'I.2.11; H.1.1', 'I.0', '68Q32', 'F.1.1; I.2.0', '93E03', 'I.2.6; I.2.9; I.5.2; H.1.2', 'math.AG', '00Bxx', 'I.2.6; J.4', 'I.4.6, I.2.6', 'I.2.8; G.3', '91A06, 91A20', '93E20, 93E35, 60J20', '93C85, 68T40, 68T05', 'I.2.11; I.2.9; I.2.6', '60', 'I.2.6; I.2.8; G.3', '68T05, 68Q32', 'I.2.1; I.2.8; I.6.3', '00-02', '68T05 91E40', 'cs.OS', 'I.5.2; F.2.2', '93', '68Wxx', '60-06', '74Q15, 05C99', '68T05, 68T40, 93C85', '49, 90, 93', '90C40', 'A.1, I.2, I.5, J.3', 'I.2.6; H.2.4', '68T05 (Primary), 93E35, 90C40, 93E20, 49L20 (Secondary)', 'I.2.8; I.2.6; G.3', '68T05 (Primary), 93E35, 93E20, 90C40, 49L20 (Secondary)', '62C10, 91B08, 91B10', 'G.1.6; G.3; I.2.6', 'C.2.1; C.2.2; C.2.4; C.2.6; F.1.1; I.2.6; I.2.8; I.2.9', 'H.3.3', 'I.2;I.2.9;I.2.11', 'G.2;G.1.6;I.2;I.2.6', 'adap-org', 'cond-mat', 'I.2.6 ; I.2.11', '65Z05, 65K10, 65R30, 68U10, 68T07, 65F22', 'G.1; I.2; I.4; J.3', 'I.7.5', 'I.4.0; I.4.9', 'I.2; I.4.3; I.4.4', 'I.2.6, I.2.10', 'astro-ph.SR', 'I.2.10; I.4', '62M15, 90B22, 60G55', '65D18, 68U10', '49M37, 65K10, 90C30, 90C90', '65F30', 'I.4.3; G.1.3', '65D18, 65J22, 68U10, 68Q32', 'I.2.10; I.4.3; D.1.3', '00', '62H35, 68U10, 94A08', 'I.4.3; I.4.9', '94A08, 94A12', '68U10, 62F15', 'I.4.5; I.4.4; G.3', 'I.4.5; I.2.6; I.5.1', 'I.2.9; I.2.10', '62G86', 'G.3.7; G.3.11', 'I.2.1; I.5.1; J.3', 'astro-ph.EP', 'I.4.6; I.2.6; J.2', 'H.3.3; I.2.1; J.3', '68U05, 68T30', 'J.2.5; H.4.0; I.5.1', '68T07 (Primary) 46N10, 94A17 (Secondary)', 'I.5.1; I.5.4; I.2.7; I.2.10; H.3.3', '60L10 (Primary) 60L20 (Secondary)', 'I.2.6; I.4.4', 'I.4, I.5', '68T09', '68W10, 68W15, 68W40, 90C06, 90C35', 'G.1.6; F.2.1', 'I.4.6; I.5.0; I.2.10', 'I.5.1; I.5.4; I.2.6; I.2.10', '97P30', '68T30, 68T10 (Primary)', 'I.2.4; I.5.3', '68T07 (primary), 26B40, 41A30, 35Q68', '62H30 (Primary) 14F05, 62H35 (Secondary)', 'I.6.5; I.2.6', '68T01(Primary), 68T05(Secondary)', 'I.2.6; F.2.2', 'I.4.8, I.2.10', 'I.2, I.4, I.6, I.7', 'I.2; I.4; I.6; I.7', 'I.4; I.4.6; I.2.1; I.2.10', '41A52, 41A63, 62F10, 62J05', 'F.2.2; I.4.3', 'I.4.7; I.2.10', '62H35', '68T05, 68Q32, 68W15', 'I.2.6; I.2.7; J.3', '68T42', '62M10', 'I.2.10; I.4.8; I.5.1', 'I.2.6; I.2.10; J.7', '68T10 (Primary)', 'I.4.0; I.4.10', 'I.2.0, I.2.6', '70-08', '55U99 (Primary) 68W05, 55N99 (Secondary)', 'I.2.4; I.1.3', '68T37, 68T05, 62P35', 'G.3; I.2.6; J.2', 'I.5.4; I.4.9; I.4.10; I.2.7', 'D.4.6; I.5.4', '65C60, 68U20', '62-02, 62-09, 62F07, 62F15, 62J12, 62J05, 62J99, 62M05, 05A16,\n  60J22, 92D20, 90C27, 90C59', 'G.1.2; G.1.6; G.2.1; G.3; I.2.0; I.2.6; I.2.8; I.5.1; I.6; I.6.4', '92C55', '00B25', '49J20, 65C30, 62M45', '62-07', '62L10', 'I.2.0; J.1; J.4', '68U35, 68T05, 68-04', '68W50', 'D.1.3; G.4; I.2.8; I.2.11; I.5.3; J.3', '68T07, 68T45, 68T10, 68T50, 68U35', 'I.2.0; G.3', '90C26, 62F35', 'I.2; I.5.1', 'I.3.5; I.2.6', 'I.2.6, I.5.4', 'I.2; G.3', 'I.5.1; I.5.3', '62-07, 62H30, 97N80, 65C10', 'I.2.6; I.5.2; I.6.5; G.3; G.4', '35Q68', 'I.2.10; I.4.5; I.4.8; I.4.10', '62-07, 60G10, 62M10', '62P10', '68T05, 68T10', 'I.5.3; I.5.4; I.4.9', '62-07, 42B35, 47A58, 30C40, 35P15', 'I.5.1; I.5.4; I.2', 'I.2.6; I.5.1; I.4.2', 'G.3; H.3.3; I.5.3', 'F.2.2; G.2; G.3', '94A08', 'I.4.7; I.5.3; I.6.4', 'G.1.6; I.5.3', 'I.2.6; I.2.7; H.3.1; H.3.3', 'H.3.1; H.3.3; I.2.6; I.2.7', 'I.5.1;I5.3', '49Q22, 91A12, 68T01, 90C08', '68T20, 68T10, 68T09', '68T27', 'I.2.6; J.4; K.5.2', '90-08, 62G35, 68Q25, 68W40, 68Q87, 93E10', 'J.3; I.5; I.2.6', '68T01 (Primary) 37M05, 34A99, 86-08 (Secondary)', 'J.2; I.2.m', 'I.2.6; I.4.9; I.2.10', 'I.2.6; K.3.2', 'I.4.9; I.5.0; J.3; I.2.1', '68T07, 62H30', '62-08', '68T01, 68Q32, 68T05', 'G.4; I.2.0; J.4', '68T05, 68T07', '93B35 (Primary) 68T07, 62R07 (Secondary)', 'I.2.0; I.2.6; I.2.m', 'H.1.1; I.2.11', '35CXX, 68T20', '68T05, 49N30, 93C41, 62B10, 68P30, 94A17, 94A34', 'H.1.1; H.3.3; G.3; I.1.2; I.2.6; I.4.2; I.5.3; E.4', 'I.2.0; I.2.6; I.2.7', 'I.2.6; I.2.1', 'I.2.6; H.1.2; K.4', '06A15, 06B99, 68T05, 91A80', 'I.2.6; I.2.4; I.5.3', 'I.2.6; I.2.10; I.2.1', 'I.5.0', 'I.2.3', '65D15, 68T07, 90C26', '41A30', 'I.2; J.3

In [46]:
len(list(dict_labels.keys()))

1099

In [48]:
np.average(list(dict_labels.values()))

np.float64(72.3157415832575)